name: CI

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"
  pull_request:
    branches: ["main"]
    paths:
      - ".github/workflows/ci.yml"

jobs:
  ci:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bun-version: [1.0.0]
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 20.5.1
      - name: Install dependencies
        run: npm install
      - name: Run Lint
        run: npm run lint
      - name: Run tests
        run: npm run test -- --passWithNoTests
